language: php

php:
- '7.2'

services:
- redis-server

dist: trusty
sudo: false

addons:
  apt:
    packages:
    - libhiredis-dev

cache:
  directories:
  - ~/.composer
  - ~/.php-ext

before_install:
- source <(curl -sL https://github.com/carno-php/travis-ci/raw/master/tests-prepare.sh)

install:
- composer update

script:
- testing

after_success:
- coveralls
